### ISSUE TITLE
Update WordPress.org version

### ISSUE THREAD

**Issue by pfefferle** [diso/wordpress-xrds-simple#5]
Can you push the latest version to the WP directory?

I get an `Notice: Undefined index: HTTP_ACCEPT in /Users/pfefferle/Sites/wordpress/wp-content/plugins/xrds-simple/xrds-simple.php on line 221` and this seems to be fixed in the GitHub version.

**Comment by willnorris** [comment]
I've given you admin access here on GitHub and the WordPress plugin directory.  Release away! :shipit:

**Comment by pfefferle** [comment]
OK, done :)
